In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session


/kaggle/input/sample_submission.csv
/kaggle/input/test.csv.zip
/kaggle/input/train.csv.zip
/kaggle/input/description.md
/kaggle/input/sample_submission.csv.zip
/kaggle/input/train.csv
/kaggle/input/test.csv
/kaggle/input/jigsaw-toxic-comment-classification-challenge/sample_submission.csv
/kaggle/input/jigsaw-toxic-comment-classification-challenge/test.csv.zip
/kaggle/input/jigsaw-toxic-comment-classification-challenge/train.csv.zip
/kaggle/input/jigsaw-toxic-comment-classification-challenge/description.md
/kaggle/input/jigsaw-toxic-comment-classification-challenge/sample_submission.csv.zip
/kaggle/input/jigsaw-toxic-comment-classification-challenge/train.csv
/kaggle/input/jigsaw-toxic-comment-classification-challenge/test.csv


In [3]:
print("This is Rathod Mayur || 19BCE221 || This is my 3rd practical of IRS")


This is Rathod Mayur || 19BCE221 || This is my 3rd practical of IRS


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
# I this fetch_20newsgroups dataset for make prediction using CountVectorizer.
from sklearn.datasets import fetch_20newsgroups
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics


In [5]:
corpus = ['This is the first document.',
          'This document is the second document.',
          'And this is the third one.',
          'Is this the first document?',]


In [6]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X)
vectorizer.get_feature_names_out()


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 21 stored elements and shape (4, 9)>
  Coords	Values
  (0, 8)	1
  (0, 3)	1
  (0, 6)	1
  (0, 2)	1
  (0, 1)	1
  (1, 8)	1
  (1, 3)	1
  (1, 6)	1
  (1, 1)	2
  (1, 5)	1
  (2, 8)	1
  (2, 3)	1
  (2, 6)	1
  (2, 0)	1
  (2, 7)	1
  (2, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	1
  (3, 1)	1


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [7]:
print(X.toarray())


[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [8]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names_out())
print("***Vector Repersentation***\n",X2.toarray())


['and this' 'document is' 'first document' 'is the' 'is this'
 'second document' 'the first' 'the second' 'the third' 'third one'
 'this document' 'this is' 'this the']
***Vector Repersentation***
 [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


In [9]:
# This is the Example for sklearn datasets.
# In this is I perform CountVectorizer and then make Prediction.

# Create our vectorizer
vectorizer = CountVectorizer()

train = fetch_20newsgroups(subset='train',remove=('headers', 'footers', 'quotes'))
test = fetch_20newsgroups(subset='test',remove=('headers', 'footers', 'quotes'))

# Get the training vectors
vectors = vectorizer.fit_transform(train.data)

clf = MultinomialNB(alpha=.01)
clf.fit(vectors, train.target)

# Get the test vectors
vectors_test = vectorizer.transform(test.data)

# Predict and score the vectors
pred = clf.predict(vectors_test)
acc_score = metrics.accuracy_score(test.target, pred)
f1_score = metrics.f1_score(test.target, pred, average='macro')

print('Total accuracy classification score: {}'.format(acc_score))
print('Total F1 classification score: {}'.format(f1_score))


Total accuracy classification score: 0.6460435475305364
Total F1 classification score: 0.6203806145034193


In [10]:
txt = ["He is ::having a great Time, at the park time?",
       "She, unlike most women, is a big player on the park's grass.",
       "she can't be going"]


In [11]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(txt)
print(vectorizer.get_feature_names_out())


['at' 'be' 'big' 'can' 'going' 'grass' 'great' 'having' 'he' 'is' 'most'
 'on' 'park' 'player' 'she' 'the' 'time' 'unlike' 'women']


In [12]:
print(X.shape)
X.toarray()


(3, 19)


array([[0.32049968, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.32049968, 0.32049968, 0.32049968, 0.24374827,
        0.        , 0.        , 0.24374827, 0.        , 0.        ,
        0.24374827, 0.64099936, 0.        , 0.        ],
       [0.        , 0.        , 0.32767345, 0.        , 0.        ,
        0.32767345, 0.        , 0.        , 0.        , 0.24920411,
        0.32767345, 0.32767345, 0.24920411, 0.32767345, 0.24920411,
        0.24920411, 0.        , 0.32767345, 0.32767345],
       [0.        , 0.52863461, 0.        , 0.52863461, 0.52863461,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.40204024,
        0.        , 0.        , 0.        , 0.        ]])

In [13]:
txt1 = ['His smile was not perfect', 'His smile was not not not not so perfect', 'she not sang', 'she was not perfect']
print ("The text: ", txt1)


The text:  ['His smile was not perfect', 'His smile was not not not not so perfect', 'she not sang', 'she was not perfect']


In [14]:
# This will print out a list of words used, and their index in the vectors
print('Vocabulary: ')
print(vectorizer.vocabulary_)


Vocabulary: 
{'he': 8, 'is': 9, 'having': 7, 'great': 6, 'time': 16, 'at': 0, 'the': 15, 'park': 12, 'she': 14, 'unlike': 17, 'most': 10, 'women': 18, 'big': 2, 'player': 13, 'on': 11, 'grass': 5, 'can': 3, 'be': 1, 'going': 4}


In [15]:
tf = TfidfVectorizer(smooth_idf=False, sublinear_tf=False, norm=None, analyzer='word')
txt_fitted = tf.fit(txt1)
txt_transformed = tf.fit_transform(txt1)
txt_transformed.toarray()


array([[1.69314718, 1.        , 1.28768207, 0.        , 0.        ,
        1.69314718, 0.        , 1.28768207],
       [1.69314718, 4.        , 1.28768207, 0.        , 0.        ,
        1.69314718, 2.38629436, 1.28768207],
       [0.        , 1.        , 0.        , 2.38629436, 1.69314718,
        0.        , 0.        , 0.        ],
       [0.        , 1.        , 1.28768207, 0.        , 1.69314718,
        0.        , 0.        , 1.28768207]])

In [16]:
# if we wanted to get the vector for one word:
print('Hot vector: ')
print(vectorizer.transform(['smile']).toarray())


Hot vector: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
idf = tf.idf_
print(dict(zip(txt_fitted.get_feature_names(), idf)))

# We see that the tokens 'sang','she' have the most idf weight because 
# they are the only tokens that appear in one document only.
# The token 'not' appears 6 times but it is also in all documents, so its idf is the lowest


AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [18]:
rr = dict(zip(txt_fitted.get_feature_names(), idf))


AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [19]:
token_weight = pd.DataFrame.from_dict(rr, orient='index').reset_index()
token_weight.columns=('token','weight')
token_weight = token_weight.sort_values(by='weight', ascending=False)
token_weight 


NameError: name 'rr' is not defined

In [20]:
# Plot bar graph on this txt.
sns.barplot(x='token', y='weight', data=token_weight)            
plt.title("Inverse Document Frequency(idf) per token")
fig=plt.gcf()
fig.set_size_inches(10,5)
plt.show()


NameError: name 'token_weight' is not defined

In [21]:
# get feature names 
feature_names = np.array(tf.get_feature_names())
sorted_by_idf = np.argsort(tf.idf_)

print("Features with lowest idf:\n{}".format(feature_names[sorted_by_idf[:3]]))
print("\nFeatures with highest idf:\n{}".format(feature_names[sorted_by_idf[-3:]]))


AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [22]:
train_data  =  pd.read_csv('../input/jigsaw-toxic-comment-classification-challenge/train.csv.zip')
train_data.head()


id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [23]:
train_data.describe()


toxic   severe_toxic        obscene         threat  \
count  159571.000000  159571.000000  159571.000000  159571.000000   
mean        0.095844       0.009996       0.052948       0.002996   
std         0.294379       0.099477       0.223931       0.054650   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

              insult  identity_hate  
count  159571.000000  159571.000000  
mean        0.049364       0.008805  
std         0.216627       0.093420  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000

In [24]:
test_data=pd.read_csv('../input/jigsaw-toxic-comment-classification-challenge/test.csv.zip')
test_data.head()


id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [25]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from wordcloud import WordCloud
from nltk.stem.snowball import SnowballStemmer
from sklearn.model_selection import train_test_split
import pickle
import string
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import roc_auc_score , accuracy_score , confusion_matrix , f1_score
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.feature_extraction.text import TfidfVectorizer


In [26]:
def clean_comment(text):
    text = text.lower()
    text = re.sub('','',text).strip() # remove html chars
    text = re.sub('\[|\(.*\]|\)','', text).strip() # remove text in square brackets and parenthesis
    text = text.translate(str.maketrans('', '', string.punctuation)) # remove punctuation marks
    text = re.sub("(\\W)"," ",text).strip() # remove non-ascii chars
    text = re.sub('\S*\d\S*\s*','', text).strip()  # remove words containing numbers
    return text.strip()


In [27]:
# First convert into string
train_data.comment_text = train_data.comment_text.astype(str)

# now clean the data using clean_comment.
train_data.comment_text = train_data.comment_text.apply(clean_comment)
train_data.comment_text.head()


0    explanation why the edits made under my userna...
1    daww he matches this background colour im seem...
2    hey man im really not trying to edit war its j...
3    more i cant make any real suggestions on impro...
4    you sir are my hero any chance you remember wh...
Name: comment_text, dtype: object

In [28]:
import nltk
from nltk.stem.snowball import SnowballStemmer
import en_core_web_sm
nlp = en_core_web_sm.load()

snow_stemmer = SnowballStemmer(language='english')

stopwords = nlp.Defaults.stop_words
def apply_stemmer(text):
    words = text.split()
    sent = [snow_stemmer.stem(word) for word in words if not word in set(stopwords)]
    return ' '.join(sent)


In [29]:
# Apply Stemming
train_data.comment_text = train_data.comment_text.apply(apply_stemmer)
train_data.comment_text.head()


0    explan edit usernam hardcor metallica fan reve...
1    daww match background colour im seem stuck tha...
2    hey man im tri edit war guy constant remov rel...
3    cant real suggest improv wonder section statis...
4                      sir hero chanc rememb page that
Name: comment_text, dtype: object

In [30]:
X = train_data.comment_text
y = train_data.drop(['id','comment_text'],axis = 1)


In [31]:
x_train,x_test,y_train,y_test =  train_test_split(X,y,test_size = 0.2,random_state = 45)


In [32]:
word_vectorizer = TfidfVectorizer(
    strip_accents='unicode',     
    analyzer='word',            
    token_pattern=r'\w{1,}',    
    ngram_range=(1, 3),         
    stop_words='english',
    sublinear_tf=True)

word_vectorizer.fit(x_train)    
train_word_features = word_vectorizer.transform(x_train)


In [33]:
X_train_transformed = word_vectorizer.transform(x_train)
X_test_transformed = word_vectorizer.transform(x_test)


In [34]:
from sklearn.multiclass import OneVsRestClassifier
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.linear_model import LogisticRegression
seed=100

log_reg = LogisticRegression(C = 10, penalty='l2', solver = 'liblinear', random_state=seed)

# fit model
classifier_ovr_log = OneVsRestClassifier(log_reg)
classifier_ovr_log.fit(X_train_transformed, y_train)


OneVsRestClassifier(estimator=LogisticRegression(C=10, random_state=100,
                                                 solver='liblinear'))

In [35]:
y_train_pred_proba = classifier_ovr_log.predict_proba(X_train_transformed)
y_test_pred_proba = classifier_ovr_log.predict_proba(X_test_transformed)


In [36]:
def make_test_predictions(df,classifier):
    df.comment_text = df.comment_text.apply(clean_comment)
    df.comment_text = df.comment_text.apply(apply_stemmer)
    X_test = df.comment_text
    X_test_transformed = word_vectorizer.transform(X_test)
    y_test_pred = classifier.predict_proba(X_test_transformed)
    return y_test_pred


In [37]:
y_pred=make_test_predictions(test_data,classifier_ovr_log)
y_pred


array([[9.99989906e-01, 3.48900753e-01, 9.99967167e-01, 4.48902405e-02,
        9.99209052e-01, 5.74793829e-01],
       [4.88663084e-03, 1.56255441e-03, 2.73185663e-03, 9.30419896e-04,
        5.74959925e-03, 1.76905706e-03],
       [9.58295835e-03, 1.63792815e-03, 4.28093789e-03, 6.22680663e-04,
        5.09035196e-03, 1.33114745e-03],
       ...,
       [1.61223427e-03, 6.17899714e-04, 2.03705319e-03, 5.16147663e-04,
        1.97307144e-03, 1.21050614e-03],
       [7.23585485e-03, 1.46190524e-03, 9.29094995e-03, 1.39539591e-03,
        9.42753384e-03, 2.03683343e-02],
       [9.97740727e-01, 2.10892788e-03, 9.36371605e-01, 4.38763697e-03,
        5.74664356e-01, 8.63002010e-03]])

In [38]:
y_pred_df = pd.DataFrame(y_pred,columns=y.columns)
y_pred_df


toxic  severe_toxic   obscene    threat    insult  identity_hate
0       0.999990      0.348901  0.999967  0.044890  0.999209       0.574794
1       0.004887      0.001563  0.002732  0.000930  0.005750       0.001769
2       0.009583      0.001638  0.004281  0.000623  0.005090       0.001331
3       0.000827      0.000617  0.000710  0.000430  0.000867       0.000376
4       0.008856      0.000373  0.004628  0.000430  0.004610       0.000736
...          ...           ...       ...       ...       ...            ...
153159  0.012474      0.001381  0.003993  0.000748  0.009043       0.001297
153160  0.063257      0.003455  0.016730  0.004961  0.026025       0.006423
153161  0.001612      0.000618  0.002037  0.000516  0.001973       0.001211
153162  0.007236      0.001462  0.009291  0.001395  0.009428       0.020368
153163  0.997741      0.002109  0.936372  0.004388  0.574664       0.008630

[153164 rows x 6 columns]

In [39]:
submission_df = pd.concat([test_data.id, y_pred_df], axis=1)
submission_df.to_csv('submission.csv', index = False)
